### ISSUE TITLE
uninitialized constant Raddocs (NameError)

### ISSUE THREAD

**Issue by lica667** [smartlogic/raddocs#25]
Hello. I am a bit lost. I use Raddocs to create api docs. but when I deploy server tells that it has an error
uninitialized constant Raddocs (NameError)
but I checked. I have this gem in project. And as I understand the error from routes   
mount Raddocs::App => "/docs"   <- in this code
what do I wrong and how can I access the generated docs?

**Comment by oestrich** [comment]
Closing due to age.
