### ISSUE TITLE
will it work with sinatra?

### ISSUE THREAD

**Issue by rubystar** [smartlogic/raddocs#26]
Hi,

I've a json api built with sinatra. Can I use this with sinatra?

**Comment by oestrich** [comment]
Raddocs is a sinatra app itself, upon a quick google it looks like you can host a sinatra app inside another sinatra app. You should also be able to host them both by using `Rack::Builder`.

**Comment by rubystar** [comment]
thanks for the response. I was able to include it in sinatra app. But the index.json is always
```ruby
{
  "resources": [

  ]
}
```

By the way my app is not using any orm, in fact it has no database.
will it work with such setup?

Thanks.
