### ISSUE TITLE
Rails 5 compatibility

### ISSUE THREAD

**Issue by micred** [smartlogic/raddocs#32]
Hi everyone, is there a way to use raddocs with Rails 5?
I found that 

```
raddocs was resolved to 1.0.1, which depends on
  sinatra (~> 1.3)
```

but sinatra needs to be the upcoming 2.0.0 (master branch) to work with Rails 5.

Can we ease the dependency to sinatra 1.*?

**Comment by veelenga** [comment]
@smartlogic any plans to support Rails 5 ? If i issue a PR for this, would you consider to review and merge it ?

**Comment by oestrich** [comment]
Once sinatra 2.0 is out we can support it. I would certainly take a look at a PR.

**Comment by bencrouse** [comment]
so now that that's merged - @oestrich are there other things you're trying to get done before releasing a Rails 5 compatible gem?

**Comment by oestrich** [comment]
I don't know of anything else that would prevent us from being rails 5 compatible. I bumped the version to 1.1, but after travis failed I'm thinking it might be good to bump to 2.0 since we're dropping ruby versions.

**Comment by tubbo** [comment]
@oestrich we bumped a major version for redis-store/redis-rack-cache on account of rack 2.0, so that might be a good idea.

**Comment by bencrouse** [comment]
@oestrich any chance you could pull the trigger on this in the near future?

**Comment by oestrich** [comment]
@bencrouse Yeah, I just pushed `2.0.0` to master. Once it passes travis I'll push the gem up

**Comment by oestrich** [comment]
It is out!

**Comment by bencrouse** [comment]
thanks @oestrich! appreciate this gem and your work on it. 🙂
