### ISSUE TITLE
rspec_api_documentation resources can have explanations. So why they don't show in raddocs html?

### ISSUE THREAD

**Issue by mikemarsian** [smartlogic/raddocs#40]
https://stackoverflow.com/questions/49612463/rspec-api-documentation-resources-can-have-explanations-so-why-they-dont-show

**Comment by oestrich** [comment]
What version of raddocs are you using? I added 2.2.0 (what's on rubygems) to a project and got resource explanations along with example explanations showing up.

**Comment by mikemarsian** [comment]
@oestrich I was using 1.1. Tried now to update to 2.2.0, but it depends on sinatra 2.0, which doesn't coexist happily with rails 4.2.

**Comment by oestrich** [comment]
You can probably switch to using this ref 93d1c77bf4503607e95b21bcb84010e321616d90 if you're stuck on 4.2

**Comment by mikemarsian** [comment]
@oestrich just did that, it works. Thanks!
